name: Code Style check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install flake8
      run: |
        python -m pip install flake8

    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics
